### ISSUE TITLE
失效了吗

### ISSUE THREAD

**Issue by i110077** [mpco/AlfredWorkflow-Calibre-Search#5]
非常棒的作品，但是输入内容没有任何反应，是否失效？

**Comment by suliveevil** [comment]
同上问题
Alfred v4.6.1 (1274)
Model Identifier: MacBookAir10,1
System Version: macOS 12.2 (21D5025f)

```shell
[18:39:02.463] Logging Started...
[18:39:07.930] Calibre Search[Script Filter] Queuing argument 'vim'
[18:39:08.183] Calibre Search[Script Filter] Script with argv 'vim' finished
[18:39:08.186] ERROR: Calibre Search[Script Filter] Code 1: Traceback (most recent call last):
  File "main.py", line 190, in <module>
    main(querySQL)
  File "main.py", line 96, in main
    bookFullPath = os.path.join(libraryPath, bookPath, bookFilename + "." + bookFormat.lower())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 26: ordinal not in range(128)
```

**Comment by kaqijiang** [comment]
可以试试这个，我自己用python3重写了大部分的日常使用工具。Alfred5 +Python3就行
https://github.com/kaqijiang/MyToolBox-AlfredWorkflow

**Comment by yellowsoar** [comment]
@i110077  @suliveevil 
試試看在環境變數加上 `PATH=/usr/local/bin:$PATH`
![2024-05-29_15-56-02](https://github.com/mpco/AlfredWorkflow-Calibre-Search/assets/4775704/6f3ec509-5474-463b-b2cf-c79bc5de9ba3)
